name: tarea_1
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=3.7.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  cupertino_icons: ^1.0.8
  country_flags: ^3.2.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true
  fonts:
    - family: Hiatus
      fonts:
        - asset: fonts/Hiatus-Regular.ttf
        - asset: fonts/Hiatus-Regular.otf
  assets:
    - assets/images/wallpaper.jpg
    - assets/images/Rectangle988.png
    - assets/images/down-arrow.png
    - assets/images/tone.png
    - assets/images/Search.png
    - assets/images2/location2.png
    - assets/images2/location1.png
    - assets/images2/shape_star.png
    - assets/images2/tone_star.png
    - assets/images2/heart.png
    - assets/images2/location3.png
    - assets/images2/location4.png
    - assets/NavBar/Fill.png
    - assets/NavBar/Home.png
    - assets/NavBar/Ticket.png
    - assets/facilities/facilitie1.png
    - assets/facilities/facilitie2.png
    - assets/facilities/facilitie3.png
    - assets/facilities/facilitie4.png
    